spring:
  application:
    name: OJMJ-rest-api-dev
  profiles:
    active: dev

server:
  port: 8080

---

spring:
  application:
    name: OJMJ-rest-api
  profiles:
    active: prod

server:
  port: 8081